### ISSUE TITLE
Typo in Part 1 Basics

### ISSUE THREAD

**Issue by hui444** [fangpinsern/ProjectBayfont#1]
> After the request is routed, if will call a function in NodeJs.

Should be **it** instead of _if_.

Also, can consider: 
....After the request is routed, it will call a function in NodeJS, also commonly known as a controller. This is where all the logic runs....

Instead of:
> After the request is routed, if will call a function in NodeJs.
> 
> This is commonly called a controller.
> 
> Here, all the logic will run.

**Comment by fangpinsern** [comment]
fix #2
